print("Enter the name of your city: ")
city = input()
print("Enter the last thing you ate/drank:")
dish = input()
print("Enter the name of your favourite animal:")
animal = input()
print("Your superhero name is: ", city, " ", dish, " ", animal) 
